---
- name: Generate Home Assistant Automation
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Generate Home Assistant Automation
      template:
        src: template.j2
        dest: automation.yaml
